[workspace]
resolver = "3"
members = [
    "types",
    "async",
    "blocking",
    "examples/event_printer",
    "examples/system_info",
    "examples/multi_client",
    "examples/multi_client_async",
]
