[package]
name = "event_printer"
version = "1.0.0"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2024"

[dependencies]
syncthing-async = { path = "../../async" }
futures-util = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
