[package]
name = "system_info"
version = "1.0.0"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2024"

[dependencies]
syncthing-async = { path = "../../async" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
